### PR TITLE
community.html: update vision link

### PR DESCRIPTION
**Pull request by maribu**
Now that the vision is in the official home of doc, let's update the links.

### CODE REVIEW

**Comment by waehlisch** [comment]
i don't like this option. as the vision is now a md file, we can directly integrate the file into the website, e.g., by dynamically fetching from the git repo.

**Comment by chrysn** [comment]
An inclusion can be a good next step, although given the current drive to collect documentation centrally from the previously spread-out sources, that should go with some clear indication on where that "sits". (Like, a "view this as part of the documentation, or edit on GitHub" style link).

At any rate, this is a good fix.

**Comment by maribu** [comment]
I wonder if from a technical point of view it would make more sense to just move the markdown into this repo, then. Otherwise we would have to make sure that the website stays in sync with main repository.

Note that moving the markdown for the vision in this repo would have to be carefully synchronized with https://github.com/RIOT-OS/RIOT/pull/20498.

Maybe it would make sense to update the vision link as an intermediate step to doc.riot-os.org? IMO the RIOT wiki looks like it is on life-support and has been for quite some time, which is not an ideal first impression. Hence, I'd rather move the attention towards the Doxygen doc and away from the Wiki :)

**Comment by miri64** [comment]
> Otherwise we would have to make sure that the website stays in sync with main repository.

That is already the case, AFAIK, because of the CPU/boards lists.

**Comment by miri64** [comment]
> i don't understand this discussion.

From my side, there is no discussion. I just wanted to clarify, that there is already a sync.

**Comment by miri64** [comment]
So, shall we update the link for now and then update the page as suggested by @waehlisch in a follow-up?

**Comment by maribu** [comment]
Given that the vision on Doxygen has already been diverged from the one in the Wiki, how about updating this? I would also like to remove the copy from the Wiki once the links there are dropped.

**Review by miri64 — APPROVED** [review]
ACK. If I have a bored hour or two in the coming time, I can look into the page re-design @waehlisch was asking for. I imagine keeping that card, but linking to another section on `community.html` that includes the vision.md from `_RIOT/doc/doxygen/src`. I will open an issue as a reminder.

**Comment by miri64** [comment]
See #126

**Pull request merged**
