### PR TITLE
add matrix link to social-media

### PR DESCRIPTION
**Pull request by kfessel**
no matrix logo on https://remixicon.com/

could also use the disqus logo `<i class="ri-disqus-fill"></i>` for disqus which would free the chat logo

or the `<i class="ri-chat-smile-fill"></i>` for `https://matrix.org/`, that would slightly resemble their chat logo or an `[m]`

### CODE REVIEW

**Comment by leandrolanzieri** [comment]
Yeah, there is a [request issue](https://github.com/Remix-Design/RemixIcon/issues/209) for the matrix logo for a while, but it seems that development [will be stopped for some time](https://github.com/Remix-Design/RemixIcon/issues/232). Maybe it could make sense to use [simple-icons](https://simpleicons.org/?q=matrix) for these logos? It is [recommended](https://github.com/Remix-Design/RemixIcon#icon-request) by RemixIcon, and they seem to have all the ones we need so far.

**Comment by kfessel** [comment]
https://simpleicons.org/?q=matrix
appied
some inkscape-handcraftting (reduce numer nodes)
and https://jakearchibald.github.io/svgomg/

**Comment by leandrolanzieri** [comment]
We should use the white version of the logo, also it seems a bit off-centered. If we are at it, maybe we can replace all of them?

**Comment by leandrolanzieri** [comment]
Look, they provide it as a font: https://github.com/simple-icons/simple-icons-font

**Comment by kfessel** [comment]
why didn't they write that in their page (maybe i dind lokk far enough)

**Comment by kfessel** [comment]
1MiB of font or 500B of svg even if we replace all of the it if less than 10kB

**Comment by kfessel** [comment]
see #96

**Comment by miri64** [comment]
I'm confused... wasn't this already added in https://github.com/RIOT-OS/riot-os.org/pull/87?

**Comment by miri64** [comment]
Ahhh `socialmedia.html` is not what is reached by [the navigator link "Social Media"](https://www.riot-os.org/community.html#socialmedia) but the [`<section id="social-media">` on the main page](https://www.riot-os.org/#social-media) :ballot_box_with_check:

**Comment by kfessel** [comment]
are there just 4 social links sections on that page ?

**Comment by waehlisch** [comment]
> are there just 4 social links sections on that page ?

which page? ... and whatever we currently have, might change in the future ;).

**Comment by leandrolanzieri** [comment]
#96 is in, we can close this.

**Pull request closed without merging**
