### PR TITLE
faq: update GPG key for security mailing list

### PR DESCRIPTION
**Pull request by miri64**
This adds the GPG public key and its fingerprint to the FAQ about reporting an issue.

### CODE REVIEW

**Comment by chrysn** [comment]
Does the target=_blank serve any actual purpose? If a browser decides to view it, this is just overriding that into a new tab, but being served as application/*, it opens into an application anyway. (I may be a bit behind on best practices there).

The media type is reported as application/pgp-signature, not sure whether there's a mime types list anywhere where we could look up any better extension.

**Comment by chrysn** [comment]
I checked the [database github uses](https://github.com/jshttp/mime-db/search?q=pgp), and they have no extension for application/pgp-key :-/ -- so how it is now is probably as good as it gets while we serve it through the page.

**Comment by miri64** [comment]
Removed the `target=_blank`.

**Comment by miri64** [comment]
I saw the same behavior you describe in my Firefox, but was not sure how other browsers would handle the `.asc` link (and did not care enough to test :sweat_smile:)

**Review by chrysn — APPROVED** [review]
LGTM.

We can still have improvement on how the key is deployed, how signatures come in, and in the security policy, but this is a good step.

**Review by kaspar030 — APPROVED** [review]
ACK.

**Pull request merged**
