### PR TITLE
[RFC] includes/header: include external icon and change target

### PR DESCRIPTION
**Pull request by leandrolanzieri**
## Contribution description
This PR modifies the navbar items under the "Community" section:
 - adds an icon to indicate external links, so the user is not surprised
 - changes the target of these external links to `_blank`
 - changes the order to group external and internal links

### CODE REVIEW

**Comment by miri64** [comment]
Mhh on my Laptop screen the new icons are somewhat obscured by my Firefox's the scroll bar. 

image

**Comment by miri64** [comment]
(might be just Firefox having a problem rendering on a scaled high-res display though)

**Comment by waehlisch** [comment]
@miri64 if you increase the width of your window, the clipping disappears

**Comment by miri64** [comment]
> @miri64 if you increase the width of your window, the clipping disappears

Yeah, but I assume most users don't like making their window larger than their screen (at least I don't)...

**Comment by miri64** [comment]
The screen shot from above is my default full screen view, if that was not clear...

**Review by waehlisch — COMMENTED** [review]
i would revert the order change:  the order should reflect "popularity" or "importance" instead of whether this is an external or internal link

**Comment by leandrolanzieri** [comment]
> The screen shot from above is my default full screen view, if that was not clear...

What are the viewport dimensions?

**Comment by miri64** [comment]
1213x6579

**Comment by leandrolanzieri** [comment]
> i would revert the order change: the order should reflect "popularity" or "importance" instead of whether this is an external or internal link

Done. Also fixed some missing closing `li` tags.

**Comment by leandrolanzieri** [comment]
> Mhh on my Laptop screen the new icons are somewhat obscured by my Firefox's the scroll bar.
> 
> image
> 
> On a 1080p screen it isn't a problem though.

The dropdowns should be end-aligned now, please take a look :)

**Comment by miri64** [comment]
> The dropdowns should be end-aligned now, please take a look :)

Yepp, UX is much nicer now!

image

**Comment by waehlisch** [comment]
> > i would revert the order change: the order should reflect "popularity" or "importance" instead of whether this is an external or internal link
> 
> Done. Also fixed some missing closing `li` tags.

thanks. can you change to: Forum, GitHub, Social Media, Branding, Code of Conduct -- i think we want to guide people quickly to place where they can do q&a and find the code.

**Comment by leandrolanzieri** [comment]
> can you change to: Forum, GitHub, Social Media, Branding, Code of Conduct -- i think we want to guide people quickly to place where they can do q&a and find the code.

Done!

**Comment by leandrolanzieri** [comment]
Good to go here?

**Comment by miri64** [comment]
> Good to go here?

From my side, yes.

**Review by waehlisch — APPROVED** [review]

**Pull request merged**
