### PR TITLE
branding: fix sample sizes and use vector logo

### LINKED ISSUE #75: branding page: cards exhibit different heights
The RIOT logo card is smaller in height compared to color and font cards. also, the width of the card does not always fit.

image

### PR DESCRIPTION
**Pull request by leandrolanzieri**
## Contribution description
This improves the sizes of the samples in the branding page. Also uses now a vector version of the logo.

Fixes #75

### CODE REVIEW

**Comment by waehlisch** [comment]
thanks! the size of the font box should have the same size compared to the logo box.
also, i think the gray background that we had was helpful.

currently, it doesn't look clean in same cases ;)
image

**Comment by leandrolanzieri** [comment]
> currently, it doesn't look clean in same cases ;)

Do you mean, that it should not have a 100% width?

**Comment by waehlisch** [comment]
> > currently, it doesn't look clean in same cases ;)
> 
> Do you mean, that it should not have a 100% width?

exactly.

**Comment by leandrolanzieri** [comment]
Done, now the font sample is next to the logo and in smaller viewports they are 6 columns wide. Also added back the background color.

**Comment by waehlisch** [comment]
hmm, the order is sub-optimal. the color information should be closer to the logo compared to the font because the colors refer to the logo, the font does not. sorry about the nitpicking.

i suppose this was the reason why the very original version consisted of three rows, logo, colors, and font.

**Comment by leandrolanzieri** [comment]
> hmm, the order is sub-optimal. the color information should be closer to the logo compared to the font because the colors refer to the logo, the font does not.

Well, it seems to me that Miso is used for 3 out of 4 letters in the logo, right? So it's kind of related.

> i suppose this was the reason why the very original version consisted of three rows, logo, colors, and font.

I modified it to show 3 rows in smaller viewports, the large one still shows 4 columns, should I adapt it to show always 3 rows?

**Review by waehlisch — APPROVED** [review]

**Pull request merged**
