### PR TITLE
use cases: add Savoir-faire Linux logo

### PR DESCRIPTION
**Pull request by waehlisch**

### CODE REVIEW

**Review by leandrolanzieri — APPROVED** [review]

**Comment by miri64** [comment]
I can't see the logo [here](https://riot-os-riot-os-org-preview-48.surge.sh/#use-cases-carousel).

**Comment by leandrolanzieri** [comment]
> I can't see the logo [here](https://riot-os-riot-os-org-preview-48.surge.sh/#use-cases-carousel).

I see it in the logo wall.

logo_in_website

**Comment by miri64** [comment]
For some reason, my Firefox loads the logo as a 0x0 image:
Screenshot from 2021-03-12 15-51-18
I can confirm that with Chromium the logo shows as expected.

**Comment by leandrolanzieri** [comment]
> For some reason, my Firefox loads the logo as a 0x0 image:
> 
> _edit:_ If I open the logo on its own in a separate tab, I can see it there.
> 
Interesting... I can reproduce locally with Firefox. I'm not sure what could be...

**Comment by leandrolanzieri** [comment]
Might be related to https://bugzilla.mozilla.org/show_bug.cgi?id=700533 ?

**Comment by leandrolanzieri** [comment]
Could be that the Locha SVG is defining dimensions and this one is not:
https://github.com/RIOT-OS/riot-os.org/blob/5f5e65a2a283edbb2d558c1dce426bf7f3ce4520/assets/img/use-cases/logos/lochamesh-logo.svg#L3

**Comment by leandrolanzieri** [comment]
See #50

**Comment by miri64** [comment]
Apparently, we still are in a time where you need to check your website in a handful of browsers ;-(

**Pull request merged**
