### PR TITLE
footer: Add link to riot-os.org GitHub repo

### PR DESCRIPTION
**Pull request by miri64**
Fixes https://github.com/RIOT-OS/riot-os.org/issues/79 and follows the suggestion by @sirocyl.

### CODE REVIEW

**Comment by miri64** [comment]
> (2) Imprint and text about repo should have the same font size as the copyright notice.

https://github.com/RIOT-OS/riot-os.org/pull/120

**Comment by sirocyl** [comment]
> (1) not really convinced. at least i would put the text about the repo before the Imprint, and i would shorten the text, e.g., "Git repo of this Website" or just "Repo of this Website". (2) Imprint and text about repo should have the same font size as the copyright notice.

Agreed; I could suggest "Page source" or "Website source" as alternatives. No need to specifically mention GitHub there IMO.

**Comment by miri64** [comment]
I applied your proposals and based this on #120 to unify the font size.

**Comment by miri64** [comment]
I also added a corresponding question to the FAQ, as per the proposal in #79.

**Comment by maribu** [comment]
Ping?

**Comment by miri64** [comment]
@waehlisch does the current state convince you more?

**Comment by waehlisch** [comment]
i would change the order to

© 2013 - 2024. All Rights Reserved  | [Website Source](https://github.com/RIOT-OS/riot-os.org) | [Imprint](https://riot-os-riot-os-org-preview-119.surge.sh/imprint.html)

**Comment by miri64** [comment]
Done

**Review by sirocyl — APPROVED** [review]
lgtm :+1:

**Review by waehlisch — APPROVED** [review]

**Pull request merged**
