### PR TITLE
assets/pdfs: added Martine's master thesis

### PR DESCRIPTION
**Pull request by OlegHahm**
Put the document on the web page for linking from the docs (https://doc.riot-os.org/group__net__gnrc.html - current link is down).

### CODE REVIEW

**Comment by miri64** [comment]
There used to be also a slide set.

**Review by miri64 — DISMISSED** [review]
Can we rename the directory to `assets/docs`? `assets/pdfs` seems a little weird. Do only PDFs belong in their? What about other documents?

**Comment by OlegHahm** [comment]
> Can we rename the directory to `assets/docs`? `assets/pdfs` seems a little weird. Do only PDFs belong in their? What about other documents?

Personally, I don't care. So far, we only have PDFs and from the top of my head I don't see any other document format that I could imagine to share here. I don't have any objections, but I think that's also unrelated to this PR.

**Comment by chrysn** [comment]
The assets folder is mixed in naming anyway between intention ("branding", "fonts") and technology ("css", "js"). Whatever we use (and I'm fine with either), let's just be aware that this is a potential deep linking target, and [there is a stability promise associated with it](https://www.w3.org/Provider/Style/URI.html).

This only adds PDFs -- should there be a link there, transitively reachable from the root?

**Comment by miri64** [comment]
> […] from the top of my head I don't see any other document format that I could imagine to share here.

Hopefully some truly portable, non-proprietary document format in the future ;-).

**Comment by miri64** [comment]
> but I think that's also unrelated to this PR.

You introduced this directory in this PR, so I would not call this unrelated to this PR.

**Comment by miri64** [comment]
After some offline discussions, @chrysn and I decided for `pubs/` (for "publications") to keep it future-proof and distinguish from "documentation".

**Comment by miri64** [comment]
> You introduced this directory in this PR, so I would not call this unrelated to this PR.

Ahhhh only now that I try to start moving things I realize that the directory already existed before this PR... I'd blame it on Git having no notion of a “new directory” but I could have looked it up... Sorry. Then nvm and sorry for the noise!

**Review by miri64 — APPROVED** [review]

**Pull request merged**
