### PR TITLE
ci: fix ruby and gem version

### PR DESCRIPTION
**Pull request by MrKevinWeiss**
It seems like there is a deployment failure...

I don't really know anything about this stuff but maybe this fixes it.  There was a lot of trial and error.

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
Seems to fix Depoyment https://github.com/RIOT-OS/riot-os.org/actions/runs/9615372911

**Comment by MrKevinWeiss** [comment]
ping @leandrolanzieri @miri64

**Comment by MrKevinWeiss** [comment]
another ping

**Comment by miri64** [comment]
I have no idea of ruby configuration, but if it fixes things, lets go with it.

**Review by miri64 — APPROVED** [review]

**Pull request merged**
